os:
- osx
language: ruby
rvm:
- 2.3
osx_image: xcode8
install:
- bundle install
- eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
before_script:
   - bundle exec danger
script:
- swift test
